export {default as call} from './function/call'
export {apply} from './function/apply'
export {bind} from './function/bind'
export {debounce} from './function/debounce'
export {throttle} from './function/throttle'
export {map,reduce,filter,find,findIndex,every,some} from './array/declares'
export {unique1,unique2,unique3} from './array/unique'
export {concat} from './array/concat'
export {slice} from './array/slice'
export {flatten1,flatten2} from './array/flatten'
export {compact} from './array/compact'
export {chunk} from './array/chunk'
export {difference,differences} from './array/difference'
export {mergeArray} from './array/mergeArray'
export {pull,pullAll} from './array/pull'
export {mergeObject} from './object/mergeObject'